"""Constants for the MYPV piko integration."""
from datetime import timedelta

from homeassistant.components.sensor import SensorStateClass, SensorDeviceClass
from homeassistant.const import (
    POWER_WATT,
    ENERGY_WATT_HOUR,
    ELECTRIC_POTENTIAL_VOLT,
    ELECTRIC_CURRENT_AMPERE,
    FREQUENCY_HERTZ,
    TEMP_CELSIUS,
)

DOMAIN = "mypv"

DATA_COORDINATOR = "corrdinator"

MIN_TIME_BETWEEN_UPDATES = timedelta(seconds=10)

SENSOR_TYPES = {
    "device": ["Device", None, "", "data", None, None],
    "acthor9s": ["Acthor 9s", None, "", "data", None, None],
    "fwversion": ["Firmware Version", None, "", "data", None, None],
    "psversion": ["Power Supply Version", None, "", "data", None, None],
    "p9sversion": ["Power Supply Version Acthor 9", None, "", "data", None, None],
    "screen_mode_flag": ["Screen Mode", None, "", "data", None, None],
    "status": ["Status", None, "", "data", None, None],
    "power": ["Power", POWER_WATT, "", "data", None, None],
    "boostpower": ["Boost Power", POWER_WATT, "", "data", None, None],
    "power_act": ["Power", POWER_WATT, "", "data", None, None],
    "power_solar_act": ["Power from solar", POWER_WATT, "", "data", None, None],
    "power_grid_act": ["Power from grid", POWER_WATT, "", "data", None, None],
    "power_ac9": ["Power Acthor 9", POWER_WATT, "", "data", None, None],
    "power_solar_ac9": ["Power from solar Acthor 9", POWER_WATT, "", "data", None, None],
    "power_grid_ac9": ["Power from grid Acthor 9", POWER_WATT, "", "data", None, None],
    "power1_solar": ["power1_solar", POWER_WATT, "", "data", None, None],
    "power1_grid": ["power1_grid", POWER_WATT, "", "data", None, None],
    "power2_solar": ["power2_solar", POWER_WATT, "", "data", None, None],
    "power2_grid": ["power2_grid", POWER_WATT, "", "data", None, None],
    "power3_solar": ["power3_solar", POWER_WATT, "", "data", None, None],
    "power3_grid": ["power3_grid", POWER_WATT, "", "data", None, None],
    "load_state": ["load_state", None, "", "data", None, None],
    "load_nom": ["load_nom", POWER_WATT, "", "data", None, None],
    "rel1_out": ["rel1_out", None, "", "data", None, None],
    "ww1target": ["target_temperature", TEMP_CELSIUS, "", "data", None, None],
    "temp1": ["Temperature 1", TEMP_CELSIUS, "", "data", None, None],
    "temp2": ["Temperature 2", TEMP_CELSIUS, "", "data", None, None],
    "temp3": ["Temperature 3", TEMP_CELSIUS, "", "data", None, None],
    "temp4": ["Temperature 4", TEMP_CELSIUS, "", "data", None, None],
    "boostactive": ["Boost active", None, "", "data", None, None],
    "legboostnext": ["legboostnext", None, "", "data", None, None],
    "date": ["Date", None, "", "data", None, None],
    "loctime": ["Loctime", None, "", "data", None, None],
    "unixtime": ["Unix time", None, "", "data", None, None],
    "wp_flag": ["wp_flag", None, "", "data", None, None],
    "wp_time1_ctr": ["wp_time1_ctr", None, "", "data", None, None],
    "wp_time2_ctr": ["wp_time2_ctr", None, "", "data", None, None],
    "wp_time3_ctr": ["wp_time3_ctr", None, "", "data", None, None],
    "pump_pwm": ["Pump PWM", None, "", "data", None, None],
    "schicht_flag": ["Schicht", None, "", "data", None, None],
    "act_night_flag": ["Night flag", None, "", "data", None, None],
    "ctrlstate": ["ctrlstate", None, "", "data", None, None],
    "blockactive": ["Block active", None, "", "data", None, None],
    "error_state": ["Error state", None, "", "data", None, None],
    "meter1_id": ["meter1_id", None, "", "data", None, None],
    "meter1_ip": ["meter1_ip", None, "", "data", None, None],
    "meter2_id": ["meter2_id", None, "", "data", None, None],
    "meter2_ip": ["meter2_ip", None, "", "data", None, None],
    "meter3_id": ["meter3_id", None, "", "data", None, None],
    "meter3_ip": ["meter3_ip", None, "", "data", None, None],
    "meter4_id": ["meter4_id", None, "", "data", None, None],
    "meter4_ip": ["meter4_ip", None, "", "data", None, None],
    "meter5_id": ["meter5_id", None, "", "data", None, None],
    "meter5_ip": ["meter5_ip", None, "", "data", None, None],
    "meter6_id": ["meter6_id", None, "", "data", None, None],
    "meter6_ip": ["meter6_ip", None, "", "data", None, None],
    "surplus": ["surplus", None, "", "data", None, None],
    "m0sum": ["Power Meter", POWER_WATT, "", "data", None, SensorDeviceClass.ENERGY],
    "m0l1": ["m0l1", None, "", "data", None, None],
    "m0l2": ["m0l2", None, "", "data", None, None],
    "m0l3": ["m0l3", None, "", "data", None, None],
    "m0bat": ["m0bat", None, "", "data", None, None],
    "m1sum": ["m1sum", None, "", "data", None, None],
    "m1l1": ["m1l1", None, "", "data", None, None],
    "m1l2": ["m1l2", None, "", "data", None, None],
    "m1l3": ["m1l3", None, "", "data", None, None],
    "m1devstate": ["m1devstate", None, "", "data", None, None],
    "m2sum": ["m2sum", None, "", "data", None, None],
    "m2l1": ["m2l1", None, "", "data", None, None],
    "m2l2": ["m2l2", None, "", "data", None, None],
    "m2l3": ["m2l3", None, "", "data", None, None],
    "m2soc": ["m2soc", None, "", "data", None, None],
    "m2state": ["m2state", None, "", "data", None, None],
    "m2devstate": ["m2devstate", None, "", "data", None, None],
    "m3sum": ["m3sum", None, "", "data", None, None],
    "m3l1": ["m3l1", None, "", "data", None, None],
    "m3l2": ["m3l2", None, "", "data", None, None],
    "m3l3": ["m3l3", None, "", "data", None, None],
    "m3soc": ["m3soc", None, "", "data", None, None],
    "m3devstate": ["m3devstate", None, "", "data", None, None],
    "m4sum": ["m4sum", None, "", "data", None, None],
    "m4l1": ["m4l1", None, "", "data", None, None],
    "m4l2": ["m4l2", None, "", "data", None, None],
    "m4l3": ["m4l3", None, "", "data", None, None],
    "m4devstate": ["m4devstate", None, "", "data", None, None],
    "ecarstate": ["ecarstate", None, "", "data", None, None],
    "ecarboostctr": ["ecarboostctr", None, "", "data", None, None],
    "mss2": ["mss2", None, "", "data", None, None],
    "mss3": ["mss3", None, "", "data", None, None],
    "mss4": ["mss4", None, "", "data", None, None],
    "mss5": ["mss5", None, "", "data", None, None],
    "mss6": ["mss6", None, "", "data", None, None],
    "mss7": ["mss7", None, "", "data", None, None],
    "mss8": ["mss8", None, "", "data", None, None],
    "mss9": ["mss9", None, "", "data", None, None],
    "mss10": ["mss10", None, "", "data", None, None],
    "mss11": ["mss11", None, "", "data", None, None],
    "volt_mains": ["Volt L1", ELECTRIC_POTENTIAL_VOLT, "", "data", None, None],
    "curr_mains": ["Current L1", ELECTRIC_CURRENT_AMPERE, "", "data", None, None],
    "volt_L2": ["Volt L2", ELECTRIC_POTENTIAL_VOLT, "", "data", None, None],
    "curr_L2": ["Current L2", ELECTRIC_CURRENT_AMPERE, "", "data", None, None],
    "volt_L3": ["Volt L3", ELECTRIC_POTENTIAL_VOLT, "", "data", None, None],
    "curr_L3": ["Current L3", ELECTRIC_CURRENT_AMPERE, "", "data", None, None],
    "volt_out": ["Volt out", ELECTRIC_POTENTIAL_VOLT, "", "data", None, None],
    "freq": ["Frequency", FREQUENCY_HERTZ, "", "data", None, None],
    "temp_ps": ["Temp power supply", TEMP_CELSIUS, "", "data", None, None],
    "fan_speed": ["Fan speed", None, "", "data", None, None],
    "ps_state": ["Power supply state", None, "", "data", None, None],
    "cur_ip": ["IP", None, "", "data", None, None],
    "cur_sn": ["Serial number", None, "", "data", None, None],
    "cur_gw": ["Gateway", None, "", "data", None, None],
    "cur_dns": ["DNS", None, "", "data", None, None],
    "fwversionlatest": ["latest Firmware version", None, "", "data", None, None],
    "psversionlatest": ["latest Power supply version", None, "", "data", None, None],
    "p9sversionlatest": ["latest Power supply version Acthor 9", None, "", "data", None, None],
    "upd_state": ["Update state", None, "", "data", None, None],
    "upd_files_left": ["Update files left", None, "", "data", None, None],
    "ps_upd_state": ["Power supply update state", None, "", "data", None, None],
    "p9s_upd_state": ["Acthor 9 Power supply update state", None, "", "data", None, None],
    "ret_grid_power": ["Return Grid Power", ENERGY_WATT_HOUR, "", "data" , SensorStateClass.TOTAL_INCREASING, SensorDeviceClass.ENERGY],
    "grid_power_consumption": ["Grid Power Consumption", ENERGY_WATT_HOUR, "", "data" ,  SensorStateClass.TOTAL_INCREASING, SensorDeviceClass.ENERGY],
    "energy_consumption": ["Energy Consumption", ENERGY_WATT_HOUR, "", "data" ,  SensorStateClass.TOTAL_INCREASING, SensorDeviceClass.ENERGY],
    "mainmode": ["Operating Mode", None, "", "setup", None, None],
    "mode9s": ["Operating Mode Acthor 9", None, "", "setup", None, None],
}
