"""Constants for the myPV piko integration."""
from datetime import timedelta

from homeassistant.const import (
    UnitOfPower,
    UnitOfElectricPotential,
    UnitOfElectricCurrent,
    UnitOfFrequency,
    UnitOfTemperature,
    UnitOfTime,
    PERCENTAGE,
    Platform,
)

DOMAIN = "mypv"

PLATFORMS = [Platform.SENSOR]

DATA_COORDINATOR = "coordinator"

MIN_TIME_BETWEEN_UPDATES = timedelta(seconds=10)

# short name . long name
MYPV_DEVICES = {
    "AC ELWA-E": "elwa",
    "AC-THOR": "acthor",
    "AC-THOR 9s": "actor9s",
    "AC ELWA-2": "elwa2",
    "Wi-Fi Meter": "meter",
}

# sensor_type: [name, unit, icon, page, devices]
SENSOR_TYPES = {
    "device": ["Device", None, "", "data", []],
    "acthor9s": ["AC-THOR 9s", None, "", "data", []],
    "fwversion": ["Firmware Version", None, "mdi:numeric", "data", []],
    "psversion": ["Power supply Version", None, "", "data", []],
    "p9sversion": ["Power supply Version AC-THOR 9", None, "", "data", []],
    "screen_mode_flag": ["Screen Mode", None, "", "data", []],
    "status": ["Status ID", None, "", "data", ["elwa", "acthor", "acthor9s", "elwa2"]],
    "power": ["Current consumption", UnitOfPower.WATT, "", "data", ["elwa"]],
    "boostpower": [
        "Hotwater boost",
        UnitOfPower.WATT,
        "mdi:thermometer-chevron-up",
        "data",
        ["elwa"],
    ],
    "power_act": ["Power AC-THOR", UnitOfPower.WATT, "", "data", ["acthor"]],
    "power_solar_act": [
        "Power from solar",
        UnitOfPower.WATT,
        "mdi:solar-power-variant",
        "data",
    ],
    "power_grid_act": [
        "Power from grid",
        UnitOfPower.WATT,
        "mdi:transmission-tower-import",
        "data",
        [],
    ],
    "power_ac9": ["Power AC-THOR 9", UnitOfPower.WATT, "mdi:lightning-bolt", "data", []],
    "power_solar_ac9": ["Power from solar AC-THOR 9", UnitOfPower.WATT, "mdi:solar-power-variant", "data", []],
    "power_grid_ac9": ["Power from grid AC-THOR 9", UnitOfPower.WATT, "mdi:transmission-tower-import", "data", []],
    "power1_solar": ["power1_solar", UnitOfPower.WATT, "", "data", []],
    "power1_grid": ["power1_grid", UnitOfPower.WATT, "", "data", []],
    "power2_solar": ["power2_solar", UnitOfPower.WATT, "", "data", []],
    "power2_grid": ["power2_grid", UnitOfPower.WATT, "", "data", []],
    "power3_solar": ["power3_solar", UnitOfPower.WATT, "", "data", []],
    "power3_grid": ["power3_grid", UnitOfPower.WATT, "", "data", []],
    "load_state": ["load_state", None, "", "data", []],
    "load_nom": ["load_nom", UnitOfPower.WATT, "", "data", []],
    "rel1_out": ["rel1_out", None, "", "data", []],
    "ww1target": [
        "Target temperature",
        UnitOfTemperature.CELSIUS,
        "mdi:thermometer-auto",
        "data",
        [],
    ],
    "temp1": [
        "Storage temperature 1",
        UnitOfTemperature.CELSIUS,
        "mdi:thermometer-water",
        "data",
        [],
    ],
    "temp2": ["Storage temperature 2", UnitOfTemperature.CELSIUS, "", "data", []],
    "temp3": ["Storage temperature 3", UnitOfTemperature.CELSIUS, "", "data", []],
    "temp4": ["Storage temperature 4", UnitOfTemperature.CELSIUS, "", "data", []],
    "boostactive": ["Boost active", None, "mdi:thermometer-chevron-up", "data", []],
    "legboostnext": [
        "Next Legionella boost",
        UnitOfTime.DAYS,
        "mdi:bacteria",
        "data",
        [],
    ],
    "date": ["Date", None, "mdi:calendar-today", "data", []],
    "loctime": ["Local time", None, "mdi:clock-digital", "data", []],
    "unixtime": ["Unix time", None, "mdi:web-clock", "data", []],
    "wp_flag": ["wp_flag", None, "", "data", []],
    "wp_time1_ctr": ["wp_time1_ctr", None, "", "data", []],
    "wp_time2_ctr": ["wp_time2_ctr", None, "", "data", []],
    "wp_time3_ctr": ["wp_time3_ctr", None, "", "data", []],
    "pump_pwm": ["Pump PWM", None, "", "data", []],
    "schicht_flag": ["Schicht", None, "", "data", []],
    "act_night_flag": ["Night flag", None, "", "data", []],
    "ctrlstate": ["ctrlstate", None, "", "data", []],
    "blockactive": ["Block active", None, "", "data", []],
    "error_state": ["Error state", None, "", "data", []],
    "meter1_id": ["myPV meter 1 ID", None, "", "data", []],
    "meter1_ip": ["myPV meter 1 IP", None, "", "data", []],
    "meter2_id": ["myPV meter 2 ID", None, "", "data", []],
    "meter2_ip": ["myPV meter 2 IP", None, "", "data", []],
    "meter3_id": ["myPV meter 3 ID", None, "", "data", []],
    "meter3_ip": ["myPV meter 3 IP", None, "", "data", []],
    "meter4_id": ["myPV meter 4 ID", None, "", "data", []],
    "meter4_ip": ["myPV meter 4 IP", None, "", "data", []],
    "meter5_id": ["myPV meter 5 ID", None, "", "data", []],
    "meter5_ip": ["myPV meter 5 IP", None, "", "data", []],
    "meter6_id": ["myPV meter 6 ID", None, "", "data", []],
    "meter6_ip": ["myPV meter 6 IP", None, "", "data", []],
    "meter_ss": ["WiFi meter signal strength", PERCENTAGE, "", "data", []],
    "meter_ssid": ["meter_ssid", None, "", "data", []],
    "surplus": ["Surplus", UnitOfPower.WATT, "mdi:transmission-tower-export", "data", []],
    "m0sum": ["Grid 0", UnitOfPower.WATT, "mdi:transmission-tower-export", "data", []],
    "m0l1": [
        "Grid 0 L1",
        UnitOfPower.WATT,
        "mdi:transmission-tower",
        "data",
        [],
    ],
    "m0l2": [
        "Grid 0 L2",
        UnitOfPower.WATT,
        "mdi:transmission-tower",
        "data",
        [],
    ],
    "m0l3": [
        "Grid 0 L3",
        UnitOfPower.WATT,
        "mdi:transmission-tower",
        "data",
        [],
    ],
    "m0bat": [
        "Battery storage",
        UnitOfPower.WATT,
        "mdi:transmission-tower",
        "data",
        [],
    ],
    "m1sum": ["m1sum", None, "", "data"],
    "m1l1": ["m1l1", None, "", "data"],
    "m1l2": ["m1l2", None, "", "data"],
    "m1l3": ["m1l3", None, "", "data"],
    "m1devstate": ["m1devstate", None, "", "data"],
    "m2sum": ["m2sum", None, "", "data"],
    "m2l1": ["m2l1", None, "", "data"],
    "m2l2": ["m2l2", None, "", "data"],
    "m2l3": ["m2l3", None, "", "data"],
    "m2soc": ["m2soc", None, "", "data"],
    "m2state": ["m2state", None, "", "data"],
    "m2devstate": ["m2devstate", None, "", "data"],
    "m3sum": ["m3sum", None, "", "data"],
    "m3l1": ["m3l1", None, "", "data"],
    "m3l2": ["m3l2", None, "", "data"],
    "m3l3": ["m3l3", None, "", "data"],
    "m3soc": ["m3soc", None, "", "data"],
    "m3devstate": ["m3devstate", None, "", "data"],
    "m4sum": ["m4sum", None, "", "data"],
    "m4l1": ["m4l1", None, "", "data"],
    "m4l2": ["m4l2", None, "", "data"],
    "m4l3": ["m4l3", None, "", "data"],
    "m4devstate": ["m4devstate", None, "", "data"],
    "ecarstate": ["E-Auto Status", None, "mdi:car-electric", "data", []],
    "ecarboostctr": ["ecarboostctr", None, "", "data", []],
    "mss2": ["mss2", None, "", "data"],
    "mss3": ["mss3", None, "", "data"],
    "mss4": ["mss4", None, "", "data"],
    "mss5": ["mss5", None, "", "data"],
    "mss6": ["mss6", None, "", "data"],
    "mss7": ["mss7", None, "", "data"],
    "mss8": ["mss8", None, "", "data"],
    "mss9": ["mss9", None, "", "data"],
    "mss10": ["mss10", None, "", "data"],
    "mss11": ["mss11", None, "", "data"],
    "tempchip": ["tempchip", UnitOfTemperature.CELSIUS, "", "data", []],
    "volt_mains": [
        "Mains voltage L1",
        UnitOfElectricPotential.VOLT,
        "",
        "data",
    ],
    "curr_mains": ["Mains current L1", UnitOfElectricCurrent.AMPERE, "", "data", []],
    "volt_L2": [
        "Mains voltage L2",
        UnitOfElectricPotential.VOLT,
        "",
        "data",
    ],
    "curr_L2": ["Mains current L2", UnitOfElectricCurrent.AMPERE, "", "data", []],
    "volt_L3": [
        "Mains voltage L3",
        UnitOfElectricPotential.VOLT,
        "",
        "data",
    ],
    "curr_L3": ["Mains current L3", UnitOfElectricCurrent.AMPERE, "", "data", []],
    "volt_out": [
        "Output voltage",
        UnitOfElectricPotential.VOLT,
        "",
        "data",
        [],
    ],
    "freq": ["Mains frequency", UnitOfFrequency.HERTZ, "", "data", []],
    "temp_ps": ["Temperature power supply", UnitOfTemperature.CELSIUS, "", "data", []],
    "fan_speed": ["Fan speed", None, "mdi:fan", "data", []],
    "ps_state": ["Power supply status", None, "", "data", []],
    "cur_ip": ["IP", None, "", "data", []],
    "cur_sn": ["Serial number", None, "", "data", []],
    "cur_gw": ["Gateway", None, "", "data", []],
    "cur_dns": ["DNS", None, "", "data", []],
    "fwversionlatest": ["latest Firmware version", None, "", "data", []],
    "psversionlatest": ["latest Power supply version", None, "", "data", []],
    "p9sversionlatest": ["latest Power supply version AC-THOR 9", None, "", "data", []],
    "upd_state": ["Update state", None, "", "data", []],
    "upd_files_left": ["Update files left", None, "", "data", []],
    "ps_upd_state": ["Power supply update state", None, "", "data", []],
    "p9s_upd_state": ["AC-THOR 9 Power supply update state", None, "", "data", []],
    "cloudstate": ["Cloud Status", None, "mdi:cloud-check", "data", []],
    "debug_ip": ["Debug IP", None, "", "data", []],
    # setup values
    "mainmode": ["Operating Mode", None, "", "setup", []],
    "mode9s": ["Operating Mode AC-THOR 9", None, "", "setup", []],
}
