"""Constants for the MYPV piko integration."""
from datetime import timedelta

from homeassistant.const import (
    POWER_WATT,
    ELECTRIC_POTENTIAL_VOLT,
    ELECTRIC_CURRENT_AMPERE,
    FREQUENCY_HERTZ,
    TEMP_CELSIUS,
    TIME_DAYS,
    PERCENTAGE,
    Platform,
)

DOMAIN = "mypv"

PLATFORMS = [Platform.SENSOR]

DATA_COORDINATOR = "coordinator"

MIN_TIME_BETWEEN_UPDATES = timedelta(seconds=10)

# short name . long name
MYPV_DEVICES = {
    "AC ELWA-E": "elwa",
    "AC-THOR": "acthor",
    "AC-THOR 9s": "actor9s",
    "AC ELWA-2": "elwa2",
    "Wi-Fi Meter": "meter",
}

# sensor_type: [name, unit, icon, page, devices]
SENSOR_TYPES = {
    "device": ["Device", None, "", "data", []],
    "acthor9s": ["Acthor 9s", None, "", "data", []],
    "fwversion": ["Firmware Version", None, "mdi:numeric", "data", []],
    "psversion": ["Power Supply Version", None, "", "data", []],
    "p9sversion": ["Power Supply Version Acthor 9", None, "", "data", []],
    "screen_mode_flag": ["Screen Mode", None, "", "data", []],
    "status": ["Status ID", None, "", "data", ["elwa", "acthor", "acthor9s", "elwa2"]],
    "power": ["Aktueller Verbrauch", POWER_WATT, "", "data", ["elwa"]],
    "boostpower": [
        "Warmwassersicherstellung",
        POWER_WATT,
        "mdi:thermometer-chevron-up",
        "data",
        ["elwa"],
    ],
    "power_act": ["Power AC-Thor", POWER_WATT, "", "data", ["acthor"]],
    "power_solar_act": [
        "Power from solar",
        POWER_WATT,
        "mdi:solar-power-variant",
        "data",
    ],
    "power_grid_act": [
        "Power from grid",
        POWER_WATT,
        "mdi-transmission-tower",
        "data",
        [],
    ],
    "power_ac9": ["Power Acthor 9", POWER_WATT, "", "data", []],
    "power_solar_ac9": ["Power from solar Acthor 9", POWER_WATT, "", "data", []],
    "power_grid_ac9": ["Power from grid Acthor 9", POWER_WATT, "", "data", []],
    "power1_solar": ["power1_solar", POWER_WATT, "", "data", []],
    "power1_grid": ["power1_grid", POWER_WATT, "", "data", []],
    "power2_solar": ["power2_solar", POWER_WATT, "", "data", []],
    "power2_grid": ["power2_grid", POWER_WATT, "", "data", []],
    "power3_solar": ["power3_solar", POWER_WATT, "", "data", []],
    "power3_grid": ["power3_grid", POWER_WATT, "", "data", []],
    "load_state": ["load_state", None, "", "data", []],
    "load_nom": ["load_nom", POWER_WATT, "", "data", []],
    "rel1_out": ["rel1_out", None, "", "data", []],
    "ww1target": [
        "target_temperature",
        TEMP_CELSIUS,
        "mdi:thermometer-auto",
        "data",
        [],
    ],
    "temp1": [
        "Speicher Temperatur 1",
        TEMP_CELSIUS,
        "mdi:thermometer-water",
        "data",
        [],
    ],
    "temp2": ["Temperatur 2", TEMP_CELSIUS, "", "data", []],
    "temp3": ["Temperatur 3", TEMP_CELSIUS, "", "data", []],
    "temp4": ["Temperatur 4", TEMP_CELSIUS, "", "data", []],
    "boostactive": ["Boost active", None, "mdi:thermometer-chevron-up", "data", []],
    "legboostnext": [
        "Nächster Legionellen Boost",
        TIME_DAYS,
        "mdi:bacteria",
        "data",
        [],
    ],
    "date": ["Date", None, "mdi:calendar-today", "data", []],
    "loctime": ["Lokale Uhrzeit", None, "mdi:clock-digital", "data", []],
    "unixtime": ["Unix time", None, "mdi:web-clock", "data", []],
    "wp_flag": ["wp_flag", None, "", "data", []],
    "wp_time1_ctr": ["wp_time1_ctr", None, "", "data", []],
    "wp_time2_ctr": ["wp_time2_ctr", None, "", "data", []],
    "wp_time3_ctr": ["wp_time3_ctr", None, "", "data", []],
    "pump_pwm": ["Pump PWM", None, "", "data", []],
    "schicht_flag": ["Schicht", None, "", "data", []],
    "act_night_flag": ["Night flag", None, "", "data", []],
    "ctrlstate": ["ctrlstate", None, "", "data", []],
    "blockactive": ["Block active", None, "", "data", []],
    "error_state": ["Error state", None, "", "data", []],
    "meter1_id": ["my-PV Meter 1 ID", None, "", "data", []],
    "meter1_ip": ["my-PV Meter 1 IP", None, "", "data", []],
    "meter2_id": ["my-PV Meter 2 ID", None, "", "data", []],
    "meter2_ip": ["my-PV Meter 2 IP", None, "", "data", []],
    "meter3_id": ["my-PV Meter 3 ID", None, "", "data", []],
    "meter3_ip": ["my-PV Meter 3 IP", None, "", "data", []],
    "meter4_id": ["my-PV Meter 4 ID", None, "", "data", []],
    "meter4_ip": ["my-PV Meter 4 IP", None, "", "data", []],
    "meter5_id": ["my-PV Meter 5 ID", None, "", "data", []],
    "meter5_ip": ["my-PV Meter 5 IP", None, "", "data", []],
    "meter6_id": ["my-PV Meter 6 ID", None, "", "data", []],
    "meter6_ip": ["my-PV Meter 6 IP", None, "", "data", []],
    "meter_ss": ["WiFi Meter Signalstärke", PERCENTAGE, "", "data", []],
    "meter_ssid": ["meter_ssid", None, "", "data", []],
    "surplus": ["Meter + Batterieladeleistung", POWER_WATT, "", "data", []],
    "m0sum": ["Hausanschluss", POWER_WATT, "mdi:transmission-tower", "data", []],
    "m0l1": ["Hausanschluss L1", POWER_WATT, "mdi:transmission-tower", "data", []],
    "m0l2": ["Hausanschluss L2", POWER_WATT, "mdi:transmission-tower", "data", []],
    "m0l3": ["Hausanschluss L3", POWER_WATT, "mdi:transmission-tower", "data", []],
    "m0bat": ["Batteriespeicher", POWER_WATT, "mdi:transmission-tower", "data", []],
    "m1sum": ["PV Leistung", POWER_WATT, "mdi:solar-power", "data", []],
    "m1l1": ["PV Leistung L1", POWER_WATT, "mdi:solar-power", "data", []],
    "m1l2": ["PV Leistung L2", POWER_WATT, "mdi:solar-power", "data", []],
    "m1l3": ["PV Leistung L3", POWER_WATT, "mdi:solar-power", "data", []],
    "m1devstate": ["PV Kommunikationsstatus", None, "mdi:link", "data", []],
    "m2sum": ["Batterie Leistung", POWER_WATT, "mdi:home-battery", "data", []],
    "m2l1": ["Batterie Leistung L1", POWER_WATT, "mdi:home-battery", "data", []],
    "m2l2": ["Batterie Leistung L2", POWER_WATT, "mdi:home-battery", "data", []],
    "m2l3": ["Batterie Leistung L3", POWER_WATT, "mdi:home-battery", "data", []],
    "m2soc": ["Batterie SoC", PERCENTAGE, "mdi:battery-charging-50", "data", []],
    "m2state": ["Batterie Status", None, "mdi:battery-heart-variant", "data", []],
    "m2devstate": ["Batterie Kommunikationsstatus", None, "mdi:link", "data", []],
    "m3sum": ["Ladestation Leistung", POWER_WATT, "mdi:ev-station", "data", []],
    "m3l1": ["Ladestation L1", POWER_WATT, "mdi:ev-station", "data", []],
    "m3l2": ["Ladestation L2", POWER_WATT, "mdi:ev-station", "data", []],
    "m3l3": ["Ladestation L2", POWER_WATT, "mdi:ev-station", "data", []],
    "m3soc": ["Ladestation SoC", PERCENTAGE, "mdi:battery-charging-50", "data", []],
    "m3devstate": ["Ladestation Kommunikationsstatus", None, "mdi:link", "data", []],
    "m4sum": ["Wärmepumpe Leistung", POWER_WATT, "mdi:heat-pump", "data", []],
    "m4l1": ["Wärmepumpe L1", POWER_WATT, "mdi:heat-pump", "data", []],
    "m4l2": ["Wärmepumpe L2", POWER_WATT, "mdi:heat-pump", "data", []],
    "m4l3": ["Wärmepumpe L3", POWER_WATT, "mdi:heat-pump", "data", []],
    "m4devstate": ["Wärmepumpe Kommunikationsstatus", None, "mdi:link", "data", []],
    "ecarstate": ["E-Auto Status", None, "mdi:car-electric", "data", []],
    "ecarboostctr": ["ecarboostctr", None, "", "data", []],
    "mss2": ["Sekundärregler 2 Status", None, "", "data", []],
    "mss3": ["Sekundärregler 3 Status", None, "", "data", []],
    "mss4": ["Sekundärregler 4 Status", None, "", "data", []],
    "mss5": ["Sekundärregler 5 Status", None, "", "data", []],
    "mss6": ["Sekundärregler 6 Status", None, "", "data", []],
    "mss7": ["Sekundärregler 7 Status", None, "", "data", []],
    "mss8": ["Sekundärregler 8 Status", None, "", "data", []],
    "mss9": ["Sekundärregler 9 Status", None, "", "data", []],
    "mss10": ["Sekundärregler 10 Status", None, "", "data", []],
    "mss11": ["Sekundärregler 11 Status", None, "", "data", []],
    "tempchip": ["tempchip", TEMP_CELSIUS, "", "data", []],
    "volt_mains": [
        "Eingangsspannung Leistungsteil L1",
        ELECTRIC_POTENTIAL_VOLT,
        "",
        "data",
    ],
    "curr_mains": ["Current L1", ELECTRIC_CURRENT_AMPERE, "", "data", []],
    "volt_L2": [
        "Eingangsspannung Leistungsteil L2",
        ELECTRIC_POTENTIAL_VOLT,
        "",
        "data",
    ],
    "curr_L2": ["Current L2", ELECTRIC_CURRENT_AMPERE, "", "data", []],
    "volt_L3": [
        "Eingangsspannung Leistungsteil L3",
        ELECTRIC_POTENTIAL_VOLT,
        "",
        "data",
    ],
    "curr_L3": ["Current L3", ELECTRIC_CURRENT_AMPERE, "", "data", []],
    "volt_out": [
        "AusgangsspannungLeistungsteil",
        ELECTRIC_POTENTIAL_VOLT,
        "",
        "data",
        [],
    ],
    "freq": ["Netzfrequenz", FREQUENCY_HERTZ, "", "data", []],
    "temp_ps": ["Temperatur Leistungsteil", TEMP_CELSIUS, "", "data", []],
    "fan_speed": ["Lüfterstufe", None, "mdi:fan", "data", []],
    "ps_state": ["Status Leistungsteil", None, "", "data", []],
    "cur_ip": ["IP", None, "", "data", []],
    "cur_sn": ["Serial number", None, "", "data", []],
    "cur_gw": ["Gateway", None, "", "data", []],
    "cur_dns": ["DNS", None, "", "data", []],
    "fwversionlatest": ["latest Firmware version", None, "", "data", []],
    "psversionlatest": ["latest Power supply version", None, "", "data", []],
    "p9sversionlatest": ["latest Power supply version Acthor 9", None, "", "data", []],
    "upd_state": ["Update state", None, "", "data", []],
    "upd_files_left": ["Update files left", None, "", "data", []],
    "ps_upd_state": ["Power supply update state", None, "", "data", []],
    "p9s_upd_state": ["Acthor 9 Power supply update state", None, "", "data", []],
    "cloudstate": ["Cloud Status", None, "mdi:cloud-check", "data", []],
    "debug_ip": ["Debug IP", None, "", "data", []],
    # setup values
    "mainmode": ["Operating Mode", None, "", "setup", []],
    "mode9s": ["Operating Mode Acthor 9", None, "", "setup", []],
}
